site_name: EventManager Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Modules:
    - EventManager: eventmanager.md
    - ClientEventManager: clienteventmanager.md
   # - ServerEventManager: servereventmanager.md
   # - Utilities: utilities.md

# Markdown formatting
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# LaTeX support
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-csp.js
